Adds support for integration_strategy
hashicorp/integration-release-action pull request #12
Opened 2023-05-04 18:24 UTC by BrandonRomano

2023-05-05 17:25 UTC, thiskevinwang commented on README.md
> +
Related: you'll need to update https://github.com/hashicorp/integration-release-action/blob/main/action.yml with the new `integration_strategy` input

2023-05-05 17:29 UTC, thiskevinwang commented on lib/validate-hcl.ts
> +      strategy: integrationStrategy,
(question) Are we able to avoid `@ts-ignore`, and instead cast the value to the expected type?

Something like this, on line 20

```diff
  const integrationStrategy = core.getInput("integration_strategy", {
    required: false,
+ }) as "default" | "pack" | undefined
```

2023-05-05 17:31 UTC, thiskevinwang requested changes
Look straightforwards

Don't forget to run `npm run build`!
- We should probably add a pre-commit hook or other automated check (sooner or later) so this doesn't get missed in the future.

2023-05-08 16:46 UTC, BrandonRomano commented on README.md
> +
👌 good catch

2023-05-09 16:29 UTC, thiskevinwang approved these changes
👍

2023-05-09 16:30 UTC, merged